# Copyright 2026 Yixin Ma, Oakley Martin, Hansol Lee, Kwok-Shing Chan, Hong-Hsi Lee, and Susie Huang (MGH/Martinos Center)
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
#
# With questions or issues, contact Oakley Martin at omartin3@mgh.harvard.edu
# Most recent update: 6 May 2026

import sys
import tkinter as tk
from tkinter import ttk
import tkinter.messagebox as msgbox
from tkinter import filedialog
import os
import nibabel as nib
import numpy as np
import glob
import shutil
import subprocess
import tempfile
from datetime import datetime
from pathlib import Path

# Add the current directory to Python path to ensure helpers can be imported
current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.insert(0, current_dir)

from helpers.concat_dwis import create_output_folders, get_total_runs, modify_bvals
from helpers.dcm2bids_exportparam_concat_helper import (
    dcm2bids_command,
    export_diffusion_parameters_command,
    concatenate_dwi_data_command,
)
from helpers.degibbs_helper import degibbs_commands
from helpers.topup_helper import topup_commands
from helpers.generate_masks_helper import generate_masks_commands
from helpers.eddy_helper import eddy_commands
from helpers.hhl_gnc_helper import gnc_commands
from helpers.interpolation_eddy_gnc_helper import interpolation_eddy_gnc
from helpers.hhl_gnc_anat_helper import gnc_anat_commands
from helpers.denoise_helper import denoise_commands

# Global list to store the executed commands
executed_commands = []

# FreeSurfer 8.0 environment setup
FREESURFER_ENV = """
export FREESURFER_HOME=/usr/local/freesurfer/8.0.0
export FSFAST_HOME=/usr/local/freesurfer/8.0.0/fsfast
export SUBJECTS_DIR=/usr/local/freesurfer/8.0.0/subjects
export MNI_DIR=/usr/local/freesurfer/8.0.0/mni
source $FREESURFER_HOME/SetUpFreeSurfer.sh
"""

def get_subject_ids():
    subject_ids = subj_entry.get("1.0", 'end-1c').strip()
    return [sid.strip() for sid in subject_ids.split(',') if sid.strip()]

def update_paths(*args):
    # Get all subject IDs from the entry widget
    subject_ids = get_subject_ids()
    
    # Get the bidspath from bidspath_entry
    bidspath = bidspath_entry.get("1.0", 'end-1c').strip()
    
    # Initialize the variables with default values
    new_dwi_path = ""
    new_dwi_process_path = ""
    new_anat_process_path = ""
    new_fsInput_path = ""
    new_image_to_run_gnc_path = ""

    # Check if there are valid subject IDs
    if subject_ids and bidspath:
        # For single subject, use specific path. For multiple subjects, use template
        if len(subject_ids) == 1:
            subject_id = subject_ids[0]
            # Update paths for the single subject
            new_dwi_path = f"{bidspath}/sub-{subject_id}/dwi"
            new_dwi_process_path = f"{bidspath}/sub-{subject_id}/dwi_process"
            new_anat_process_path = f"{bidspath}/sub-{subject_id}/anat_process"
            new_fsInput_path = f"{bidspath}/sub-{subject_id}/anat/sub-{subject_id}_run-02_T1w.nii.gz"
            new_image_to_run_gnc_path = f"{bidspath}/sub-{subject_id}/anat/sub-{subject_id}_run-01_T1w.nii.gz"
        else:
            # Use template for multiple subjects
            new_dwi_path = f"{bidspath}/{{subj_id}}/dwi"
            new_dwi_process_path = f"{bidspath}/{{subj_id}}/dwi_process"
            new_anat_process_path = f"{bidspath}/{{subj_id}}/anat_process"
            new_fsInput_path = f"{bidspath}/{{subj_id}}/anat/{{subj_id}}_run-02_T1w.nii.gz"
            new_image_to_run_gnc_path = f"{bidspath}/{{subj_id}}/anat/{{subj_id}}_run-01_T1w.nii.gz"
    
    # Update the GUI elements with paths
    subj_raw_dir_entry.delete("1.0", 'end')
    subj_raw_dir_entry.insert("1.0", new_dwi_path)
    
    subj_process_dir_entry.delete("1.0", 'end')
    subj_process_dir_entry.insert("1.0", new_dwi_process_path)
    
    anat_process_dir_entry.delete("1.0", 'end')
    anat_process_dir_entry.insert("1.0", new_anat_process_path)
    
    fsInput_entry.delete("1.0", 'end')
    fsInput_entry.insert("1.0", new_fsInput_path)  
    
    image_to_run_gnc_dir_entry.delete("1.0", 'end')
    image_to_run_gnc_dir_entry.insert("1.0", new_image_to_run_gnc_path)


def on_key_release(event):
    update_paths()


def append_command_to_script(command, base_dir, subject):
    script_dir = f"{base_dir}/s0_script"
    os.makedirs(script_dir, exist_ok=True)
    script_path = f"{script_dir}/{subject}_script_to_run.sh"
    
    # Check if file exists, if not create with shebang
    if not os.path.exists(script_path):
        with open(script_path, 'w') as file:
            file.write('#!/bin/bash\n\n')
            file.write('# Script generated by DWI preprocessing GUI\n')
            file.write(f'# Subject: {subject}\n')
            file.write(f'# Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n\n')
        # Make the script executable
        os.chmod(script_path, 0o755)
    
    with open(script_path, 'a') as file:
        # Add timestamp comment
        file.write(f'\n# Command added at {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n')
        
        # Handle different command formats
        if 'export' in command and '\n' in command and not '&&' in command:
            # Write environment exports as separate lines
            lines = command.strip().split('\n')
            for line in lines:
                if line.strip():
                    file.write(line.strip() + '\n')
        elif '\\' in command and '&&' in command:
            # Handle multi-line commands with backslashes (like TractSeg)
            # These are already properly formatted with line continuations
            file.write(command.strip() + '\n')
        elif '&&' in command and not '\\' in command:
            # Format multi-command lines nicely
            parts = command.split('&&')
            for i, part in enumerate(parts):
                if i == 0:
                    file.write(part.strip())
                else:
                    file.write(' && \\\n    ' + part.strip())
            file.write('\n')
        else:
            # Single line command - clean up excessive whitespace
            cleaned_command = ' '.join(command.split())
            file.write(cleaned_command + '\n')
    
    #msgbox.showinfo("Success", f"Command appended successfully to {script_path}")

def output_shell_script(commands, base_dir, subject):
    script_dir = f"{base_dir}/s0_script"
    os.makedirs(script_dir, exist_ok=True)
    script_path = f"{script_dir}/{subject}_executed_script.sh"
    
    with open(script_path, 'w') as file:
        file.write("#!/bin/bash\n\n")
        file.write("# Auto-generated script logging all preprocessing commands executed.\n\n")
        file.writelines(commands)
    
    msgbox.showinfo("Success", f"Script saved successfully to {script_path}")

def finalize_script(base_dir, subject):
    """Add a completion message to the script file"""
    script_dir = f"{base_dir}/s0_script"
    script_path = f"{script_dir}/{subject}_script_to_run.sh"
    
    if os.path.exists(script_path):
        with open(script_path, 'a') as file:
            file.write(f'\n# Script completed at {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}\n')
            file.write('echo "All processing steps completed successfully!"\n')

# Function to remove a script file
def remove_script(base_dir, subject):
    script_path = f"{base_dir}/s0_script/{subject}_script_to_run.sh"
    if os.path.exists(script_path):
        os.remove(script_path)
        msgbox.showinfo("Success", f"Script {script_path} removed successfully.")
    else:
        msgbox.showerror("Error", f"Script {script_path} does not exist.")

import threading  # Import threading module

def execute_script_commands(base_dir, subject):
    def run_script():
        script_path = f"{base_dir}/s0_script/{subject}_script_to_run.sh"
        if os.path.exists(script_path):
            with open(script_path, 'r') as file:
                for command in file:  # Read line by line
                    command = command.strip()
                    if command:  # Check if the line is not empty
                        try:
                            completed_process = subprocess.run(
                                cmd,
                                shell=True,
                                check=True,
                                stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE,
                                # no text=True here
                            )
                            
                            # Decode manually, if you know the correct encoding
                            stdout_str = completed_process.stdout.decode('latin-1', errors='replace')
                            stderr_str = completed_process.stderr.decode('latin-1', errors='replace')

                            
                            # Update the status_text widget with the command and its output
                            status_text.insert('end', f"Command executed successfully:\n{command}\nOutput:\n{stdout}\n")
                            if stderr:
                                # If there is an error message, display it as well
                                status_text.insert('end', f"Errors:\n{stderr}\n")
                            
                        except subprocess.CalledProcessError as e:
                            # If a command fails, capture the error and display it
                            status_text.insert('end', f"An error occurred:\n{e.stderr}\n")
                            break  # Stop executing the next commands if an error occurs
                        finally:
                            status_text.see('end')  # Auto-scroll to the end

            # Auto-scroll the status_text widget to the bottom after each command
            status_text.see(tk.END)
        else:
            status_text.insert('end', f"Script {script_path} does not exist.\n")
            status_text.see('end')  # Auto-scroll to the end
    
    # Create a new thread for running the script
    script_thread = threading.Thread(target=run_script)
    script_thread.start()  # Start the thread
    
def execute_command_and_log_output(cmd, success_message, subject_id=None):
    # Display the command first
    status_text.insert('end', f"Executing Command:\n{cmd}\n")
    status_text.see('end')  # Auto-scroll to the end
    
    # Append command to script file
    if subject_id:
        base_dir=f"/your/project/directory/bids/sub-{subject_id}/dwi_process"
        subject = f"sub-{subject_id}"
        append_command_to_script(cmd, base_dir, subject)
    else:
        # Try to get subject ID from current context
        subject_ids = get_subject_ids()
        if subject_ids:
            for sid in subject_ids:
                base_dir = f"/your/project/directory/bids/sub-{sid}/dwi_process"
                subject = f"sub-{sid}"
                append_command_to_script(cmd, base_dir, subject)
    
    try:
        # Run the command, capture output and errors
        completed_process = subprocess.run(cmd, shell=True, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        
        stdout = completed_process.stdout.decode('latin-1', errors='replace')
        stderr = completed_process.stderr.decode('latin-1', errors='replace')

        
        # Update the status_text widget with the command's output
        if stdout:
            status_text.insert('end', f"{success_message} Output:\n{stdout}\n")
        if stderr:
            # If there is an error message, display it as well
            status_text.insert('end', f"Errors:\n{stderr}\n")
        
    except subprocess.CalledProcessError as e:
        # If a command fails, capture the error and display it
        status_text.insert('end', f"An error occurred:\n{e.stderr}\n")
    finally:
        status_text.see('end')  # Auto-scroll to the end
    
def execute_dcm2bids():
    subject_ids = get_subject_ids()
    
    for subject_id in subject_ids:
        bidspath = bidspath_entry.get("1.0", 'end-1c').strip()
        config = config_entry.get("1.0", 'end-1c').strip()
        dcm_source = dcm_source_entry.get("1.0", 'end-1c').strip()
        cmd = dcm2bids_command(subject_id, bidspath, config, dcm_source)
        execute_command_and_log_output(cmd, f"dcm2bids executed successfully for {subject_id}.", subject_id)

def execute_export_diffusion_parameters():
    subject_ids = get_subject_ids()
    
    for subject_id in subject_ids:
        subj_raw_dir = f"/your/project/directory/bids/sub-{subject_id}/dwi"
        cmd = export_diffusion_parameters_command(subject_id, subj_raw_dir)
        execute_command_and_log_output(cmd, f"Diffusion parameters exported successfully for {subject_id}.", subject_id)

def execute_concatenate_dwi_data():
    subject_ids = get_subject_ids()
    for subject_id in subject_ids:
        # Dynamically construct paths for the current subject ID
        subj_raw_dir = f"/your/project/directory/bids/sub-{subject_id}/dwi"
        subj_process_dir = f"/your/project/directory/bids/sub-{subject_id}/dwi_process"
        
        # Update the GUI entries if needed (optional, for user feedback)
        subj_raw_dir_entry.delete("1.0", 'end')
        subj_raw_dir_entry.insert("1.0", subj_raw_dir)
        subj_process_dir_entry.delete("1.0", 'end')
        subj_process_dir_entry.insert("1.0", subj_process_dir)

        cmd = concatenate_dwi_data_command(subj_raw_dir, f'sub-{subject_id}', subj_process_dir)
        execute_command_and_log_output(cmd, f"DWI series concatenated successfully for {subject_id}.", subject_id)

def concatenate_nifti_with_mrcat(file_paths, output_file):
    """
    Uses MRtrix3's mrcat to concatenate NIfTI files along the 4th dimension.
    """
    if not file_paths:
        raise ValueError("No valid NIfTI files provided for concatenation.")
    
    status_text.insert('end', f"Concatenating NIfTI files:\n")
    for fp in file_paths:
        status_text.insert('end', f" - {fp}\n")
    status_text.insert('end', f"Output file: {output_file}\n")
    status_text.see('end')
    
    command = ['mrcat'] + file_paths + ['-axis', '3', output_file, '-force']
    subprocess.run(command, check=True)


import numpy as np

def concatenate_text_files(file_paths, output_file):
    """
    Concatenates the content of multiple text files (e.g., bvals, bvecs, etc.) into a single output file.
    Handles 1-dimensional and 2-dimensional input data (e.g., bvecs) and concatenates along the first dimension.
    All files (except bvecs and bvals) are reshaped to (1, N).
    
    Parameters:
    - file_paths: List of file paths to be concatenated.
    - output_file: The output file where the concatenated data will be written.
    """
    try:
        concatenated_data = []

        # Define file names that are treated differently
        bvecs_file = "bvec"
        bvals_file = "bval"

        # Read and process each file
        for file_path in file_paths:
            with open(file_path, 'r') as file:
                # Load data into an array, split lines and then split elements on each line
                data = [line.strip().split() for line in file.readlines()]
                
                # Convert the list of lists into a numpy array
                data_array = np.array(data, dtype=float)

                # Check the shape of the data and handle it appropriately
                if bvecs_file in file_path:  # Shape (3, N) for bvecs
                    concatenated_data.append(data_array)
                elif bvals_file in file_path:  # Shape (1, N) for bvals
                    concatenated_data.append(data_array.flatten())
                else:
                    # Reshape all other files to (1, N)
                    concatenated_data.append(data_array.flatten().reshape(1, -1))

        # Concatenate all data along the first dimension
        concatenated_result = np.concatenate(concatenated_data, axis=1) if concatenated_data[0].ndim == 2 else np.concatenate(concatenated_data)

        # Save the concatenated result to the output file
        np.savetxt(output_file, concatenated_result, fmt='%g')
        
        print(f"Concatenation successful! Output written to {output_file}.")
    
    except FileNotFoundError as fnf_error:
        print(f"Error: One of the files was not found: {fnf_error}")
    except ValueError as ve:
        print(f"Error: {ve}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")



def concatenate_files(nii_paths, output_base, subject_id):
    """
    Concatenates DWI NIfTI files and their corresponding parameter files.
    """
    # Create the output directory if it doesn't exist
    output_dir = os.path.join(output_base, 's1_concat')
    os.makedirs(output_dir, exist_ok=True)
    
    # Concatenate NIfTI files
    output_nii_file = os.path.join(output_dir, f"sub-{subject_id}_dwi.nii.gz")
    concatenate_nifti_with_mrcat(nii_paths, output_nii_file)
    
    # File types to concatenate along with NIfTI files
    file_types = ['bval', 'bvec', 'phaseEncoding', 'diffusionTime', 'pulseWidth']
    
    for file_type in file_types:
        # For each DWI file, get the corresponding supporting file path
        file_paths = []
        for nii_path in nii_paths:
            base_path = nii_path.replace('.nii.gz', '')
            supporting_file = f"{base_path}.{file_type}"
            if os.path.exists(supporting_file):
                file_paths.append(supporting_file)
            else:
                status_text.insert('end', f"Warning: {file_type} file not found for {nii_path}\n")
        
        if not file_paths:
            status_text.insert('end', f"No {file_type} files found for concatenation for subject {subject_id}.\n")
            continue  # Skip to next file type
        
        output_file_type = os.path.join(output_dir, f"sub-{subject_id}.{file_type}")
        concatenate_text_files(file_paths, output_file_type)

def concatenate_dwi_data_from_gui_entries():
    """
    Concatenates DWI data and related parameter files based on paths provided through the GUI.
    """
    # Fetch a list of subject IDs
    subject_ids = get_subject_ids()
    
    for subject_id in subject_ids:
        output_base = subj_process_dir_entry.get("1.0", "end-1c").strip()
        output_dir = os.path.join(output_base, 's1_concat')
        create_output_folders(output_dir)
        
        # Reading NIfTI file paths from the GUI entries and filtering out empty entries
        nii_paths = [entry.get("1.0", "end-1c").strip() for entry in dwi_file_entries]
        nii_paths = [path for path in nii_paths if path and os.path.exists(path)]
        
        if not nii_paths:
            status_text.insert('end', f"No valid NIfTI files provided for subject {subject_id}.\n")
            status_text.see('end')
            continue  # Skip to next subject
        
        # Calculate the number of volumes for each run (if needed)
        n_volumes_per_file = [nib.load(path).shape[-1] for path in nii_paths]
        
        # Concatenate NIfTI files and parameter files
        concatenate_files(nii_paths, output_base, subject_id)
        
        # Modify bvals as necessary
        output_dir = os.path.join(output_base, 's1_concat')
        input_bval_file = os.path.join(output_dir, f"sub-{subject_id}.bval")
        output_bval_file = os.path.join(output_dir, f"sub-{subject_id}.bval_mod")
        modify_bvals(input_bval_file, output_bval_file)
        
        status_text.insert('end', f"Processing complete. Concatenated files are saved in {output_dir}\n")
        status_text.see('end')

def execute_denoise():
    # Fetch a list of subject IDs
    subject_ids = get_subject_ids()
    
    # Retrieve the denoise option value
    denoise_option_value = denoise_option.get()
    
    # Skip the denoise process if 'No Denoise' is selected
    if denoise_option_value == "no_denoise":
        status_text.insert('end', "Denoise skipped as per the selected option.\n")
        status_text.see('end')
        return
    
    # Iterate over each subject ID
    for subject_id in subject_ids:
        # Construct the subject and base_dir for the current subject ID
        subject = f'sub-{subject_id}'
        base_dir=f"/your/project/directory/bids/sub-{subject_id}/dwi_process"
        
        subj_process_dir_entry.delete("1.0", 'end')
        subj_process_dir_entry.insert("1.0", base_dir)
        
        cmd = denoise_commands(subject, base_dir, denoise_option_value)
        
        execute_command_and_log_output(cmd, f"{denoise_option_value.capitalize()} denoise completed successfully for {subject_id}.", subject_id)

def execute_degibbs():
    subject_ids = get_subject_ids()
    for subject_id in subject_ids:
        subject = f'sub-{subject_id}'
        base_dir=f"/your/project/directory/bids/sub-{subject_id}/dwi_process"
        selected_flow_value = selected_flow.get()
        
        subj_process_dir_entry.delete("1.0", 'end')
        subj_process_dir_entry.insert("1.0", base_dir)

        cmd = degibbs_commands(subject, base_dir, selected_flow_value)
        execute_command_and_log_output(cmd, f"Degibbs completed successfully for {subject_id}.", subject_id)
        
def execute_topup():
    subject_ids = get_subject_ids()
    selected_flow_value = selected_flow.get()

    # <-- Retrieve the user-specified volume indices from the GUI
    pa_volume_str = pa_volume_entry.get("1.0", "end-1c").strip()
    ap_volume_str = ap_volume_entry.get("1.0", "end-1c").strip()
    
    # Convert to int (optionally handle errors or default fallback)
    try:
        pa_volume_index = int(pa_volume_str)
    except ValueError:
        pa_volume_index = 9  # Fallback default if user typed something invalid
    
    try:
        ap_volume_index = int(ap_volume_str)
    except ValueError:
        ap_volume_index = 10  # Fallback default if user typed something invalid

    for subject_id in subject_ids:
        subject = f'sub-{subject_id}'
        base_dir=f"/your/project/directory/bids/sub-{subject_id}/dwi_process"
        subj_process_dir_entry.delete("1.0", 'end')
        subj_process_dir_entry.insert("1.0", base_dir)
        
        # Pass these indices to topup_commands
        topup_cmds = topup_commands(base_dir, subject, selected_flow_value, 
                                    pa_volume_index, ap_volume_index)
        
        # Execute each command in topup_cmds
        for cmd in topup_cmds:
            execute_command_and_log_output(cmd, f"TopUp processing completed successfully for {subject_id}.", subject_id)


def execute_generate_masks():
    subject_ids = get_subject_ids()
    selected_flow_value = selected_flow.get()
    for subject_id in subject_ids:
        subject = f'sub-{subject_id}'
        base_dir=f"/your/project/directory/bids/sub-{subject_id}/dwi_process"
        subj_process_dir_entry.delete("1.0", 'end')
        subj_process_dir_entry.insert("1.0", base_dir)
        cmds, temp_files = generate_masks_commands(subject, base_dir, selected_flow_value)
        for cmd in cmds:
            execute_command_and_log_output(cmd, f"Mask generation completed successfully for {subject_id}.", subject_id)
        for temp_file in temp_files:
            try:
                os.remove(temp_file)
            except OSError as e:
                print(f"Error: {e.filename} - {e.strerror}.")

def execute_eddy():
    subject_ids = get_subject_ids()
    selected_flow_value = selected_flow.get()
    for subject_id in subject_ids:
        subject = f'sub-{subject_id}'
        base_dir=f"/your/project/directory/bids/sub-{subject_id}/dwi_process"
        subj_process_dir_entry.delete("1.0", 'end')
        subj_process_dir_entry.insert("1.0", base_dir)
        cmd = eddy_commands(subject, base_dir, selected_flow_value)
        execute_command_and_log_output(cmd, f"Eddy processing completed successfully for {subject_id}.", subject_id)

def execute_gnc_dwi():
    if gnc_option.get() == "no_gnc":
        status_text.insert('end', "GNC processing skipped.\n")
        status_text.see('end')
        return
    subject_ids = get_subject_ids()

    selected_flow_value = selected_flow.get()
    gnc_option_value = gnc_option.get()
    
    for subject_id in subject_ids:
        subject = f'sub-{subject_id}'
        base_dir=f"/your/project/directory/bids/sub-{subject_id}/dwi_process"
        subj_process_dir_entry.delete("1.0", 'end')
        subj_process_dir_entry.insert("1.0", base_dir)
        cmd = gnc_commands(subject, base_dir, selected_flow_value, gnc_option_value)
        execute_command_and_log_output(cmd, f"GNC processing for DWI completed successfully for {subject_id}.", subject_id)

def execute_interpolation_eddy_gnc():
    subject_ids = get_subject_ids()  
    flow_value = selected_flow.get() 
    for subject_id in subject_ids:
        base_dir=f"/your/project/directory/bids/sub-{subject_id}/dwi_process"
        try:
            interpolation_eddy_gnc(subject_id, base_dir, flow_value)
            status_text.insert('end', f"Interpolation and Jacobian correction completed successfully for {subject_id}.\n")
        except Exception as e:
            msgbox.showerror("Error", f"An error occurred for {subject_id}: {str(e)}")
            status_text.insert('end', f"An error occurred for {subject_id}: {str(e)}\n")
        status_text.see('end')

def execute_gnc_anat():
    if gnc_anat_option.get() == "no_gnc":
        status_text.insert('end', "GNC Anat processing skipped.\n")
        status_text.see('end')
        return

    subject_ids = get_subject_ids()
    gnc_anat_option_value = gnc_anat_option.get()
    
    for subject_id in subject_ids:
        subject = f'sub-{subject_id}'
        anat_process_dir = f"/your/project/directory/bids/sub-{subject_id}/anat_process"
        image_to_run_gnc_dir = f"/your/project/directory/bids/sub-{subject_id}/anat/sub-{subject_id}_run-01_T1w.nii.gz"     
        cmd = gnc_anat_commands(subject, anat_process_dir, image_to_run_gnc_dir, gnc_anat_option_value)
        execute_command_and_log_output(cmd, f"{gnc_anat_option_value} GNC Anat completed successfully for {subject_id}.", subject_id)

def execute_commands_with_env(commands, env_exports, success_message, subject_id=None):
    # Append commands to script file if subject_id is provided
    if subject_id:
        base_dir=f"/your/project/directory/bids/sub-{subject_id}/dwi_process"
        subject = f"sub-{subject_id}"
        # Append environment setup
        append_command_to_script(env_exports.strip(), base_dir, subject)
        # Append each command
        for cmd in commands:
            append_command_to_script(cmd, base_dir, subject)
    else:
        # Try to get subject ID from current context
        subject_ids = get_subject_ids()
        if subject_ids:
            for sid in subject_ids:
                base_dir = f"/your/project/directory/bids/sub-{sid}/dwi_process"
                subject = f"sub-{sid}"
                append_command_to_script(env_exports.strip(), base_dir, subject)
                for cmd in commands:
                    append_command_to_script(cmd, base_dir, subject)
    
    # Create a temporary shell script file
    with tempfile.NamedTemporaryFile(mode='w', suffix='.sh', delete=False) as temp_script:
        script_path = temp_script.name
        # Write the environment exports and commands to the script
        temp_script.write('#!/bin/bash\n')
        temp_script.write(env_exports + '\n')
        for cmd in commands:
            temp_script.write(cmd + '\n')

    # Make the script executable
    os.chmod(script_path, 0o775)

    # Execute the script
    status_text.insert('end', f"Executing Script: {script_path}\n")
    status_text.see('end')

    try:
        completed_process = subprocess.run(
            f"/bin/bash {script_path}", shell=True, check=True,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE
        )

        stdout = completed_process.stdout.decode('latin-1', errors='replace')
        stderr = completed_process.stderr.decode('latin-1', errors='replace')


        if stdout:
            status_text.insert('end', f"{success_message}\nOutput:\n{stdout}\n")
        if stderr:
            status_text.insert('end', f"Standard Error:\n{stderr}\n")

        return True

    except subprocess.CalledProcessError as e:
        error_output = e.stderr or e.stdout
        status_text.insert('end', f"An error occurred:\n{error_output}\n")
        return False

    finally:
        status_text.see('end')
        # Clean up the temporary script file
        os.remove(script_path)

def execute_recon_all():
    """
    Executes the recon-all process for the subject specified in the anatomical processing directory.
    """
    # Fetch a list of subject IDs
    subject_ids = get_subject_ids()
    
    # Define the expert file path
    FREESURFER_HOME = "/usr/local/freesurfer/8.0.0"
    EXPERT_FILE = Path(FREESURFER_HOME) / "expert_files/HiResRecon.txt"
    
    for subject_id in subject_ids:
        subj_id = f"sub-{subject_id}"
        
        # Retrieve the anatomical processing directory from the GUI entry
        anat_process_dir_template = anat_process_dir_entry.get("1.0", 'end-1c').strip()
        
        # Replace placeholders in the anatomical processing directory path with the actual subject ID
        anat_process_dir = anat_process_dir_template.replace('{subj_id}', subj_id)
        
        # Create the anat_process directory if it doesn't exist
        if not os.path.exists(anat_process_dir):
            os.makedirs(anat_process_dir)
            status_text.insert('end', f"Created directory: {anat_process_dir}\n")
        
        # Set SUBJECTS_DIR environment variable
        SUBJECTS_DIR = anat_process_dir
        os.environ['SUBJECTS_DIR'] = SUBJECTS_DIR
        status_text.insert('end', f"Set SUBJECTS_DIR to {SUBJECTS_DIR}\n")
        
        # Change directory to SUBJECTS_DIR
        os.chdir(SUBJECTS_DIR)
        status_text.insert('end', f"Changed directory to {SUBJECTS_DIR}\n")
        
        # Retrieve the input image path from the FreeSurfer Input Image entry
        input_image_template = fsInput_entry.get("1.0", 'end-1c').strip()
        
        # Replace placeholders in the input image path with the actual subject ID
        input_image = input_image_template.replace('{subj_id}', subj_id)
        
        # Set the environment variables and source the FreeSurfer setup script
        env_exports = f"""
export FREESURFER_HOME={FREESURFER_HOME}
export FSFAST_HOME={FREESURFER_HOME}/fsfast
export SUBJECTS_DIR={SUBJECTS_DIR}
export MNI_DIR={FREESURFER_HOME}/mni
source $FREESURFER_HOME/SetUpFreeSurfer.sh
"""
        
        # Build recon-all command
        cmd_parts = [
            f"{FREESURFER_HOME}/bin/recon-all",
            "-subjid fs8",
            f"-i {input_image}",
            "-hires",
        ]
        
        # Add expert file if it exists
        if EXPERT_FILE.is_file():
            cmd_parts.append(f"-expert {EXPERT_FILE}")
        
        cmd_parts.append("-all")
        
        # Join command parts into single command
        cmd = " ".join(cmd_parts)
        
        # Execute the single recon-all command
        success = execute_commands_with_env(
            [cmd], env_exports, f"recon-all executed successfully for {subject_id}.", subject_id
        )
        if not success:
            status_text.insert('end', f"recon-all failed for {subject_id}.\n")
            continue



def MPPCA_noise():
    def mppca_noise():
    subject_ids = get_subject_ids()
    scanner_type = gnc_option.get()
    selected_flow_value = selected_flow.get()

    for subject_id in subject_ids:
        base_dir=f"/your/project/directory/bids/sub-{subject_id}/dwi_process"
        concat_dir = f"{base_dir}/s1_concat"
        eddy_dir_suffix = f"s6_denoise_degibbs_eddy" if selected_flow_value == "concat_denoise_degibbs" else "s6_degibbs_eddy"
        gnc_dir_suffix = "s7_denoise_degibbs_gnc" if selected_flow == "concat_denoise_degibbs" else "s7_gnc"

        if scanner_type == "C2":
            hhl_gnc_cmd = "gncunwarp.sh -i {base_dir}/{eddy_dir_suffix}/sub-{subject_id}_dwi_eddy.nii.gz -o {base_dir}/{gnc_dir_suffix}/sub-{subject_id}_dwi.nii.gz -g /your/project/directory/bids/code/preprocessing_dwi/gradnonlinunwarp/gradient_coefficients/coeff.grad"
        else:
            status_text.insert('end', f"Unknown scanner type: {scanner_type}. Skipping GNC processing.\n")
            return
        
        # Create noise directory with proper naming
        noise_dir_suffix = "s9_denoise_degibbs_noise" if selected_flow_value == "concat_denoise_degibbs" else "s9_noise"
        noise_dir = f"{base_dir}/{noise_dir_suffix}"
        os.makedirs(noise_dir, exist_ok=True)

        dwiextract_cmd = f"dwiextract {concat_dir}/*dwi.nii.gz -fslgrad {concat_dir}/*bvec {concat_dir}/*bval -bzero {concat_dir}/sub-{subject_id}_b0s.nii.gz -force"
        dwidenoise_cmd = f"dwidenoise {concat_dir}/sub-{subject_id}_b0s.nii.gz {concat_dir}/sub-{subject_id}_b0s_denoised.nii.gz -noise {concat_dir}/sub-{subject_id}_sigma.nii.gz -force"
        hhl_gnc_sigma_cmd = f"{hhl_gnc_cmd} -i {concat_dir}/sub-{subject_id}_sigma.nii.gz -o {noise_dir}/sub-{subject_id}_sigma.nii.gz -interp spline"
        
        # Use correct mask directory
        mask_dir_suffix = "s5_denoise_degibbs_mask" if selected_flow_value == "concat_denoise_degibbs" else "s5_mask"
        mask_dir = f"{base_dir}/{mask_dir_suffix}"
        hhl_gnc_mask_cmd = f"{hhl_gnc_cmd} -i {mask_dir}/brain_mask.nii.gz -o {mask_dir}/sub-{subject_id}_brain_mask_gnc.nii.gz -interp nn"
        hhl_gnc_wm_cmd = f"{hhl_gnc_cmd} -i {mask_dir}/wm.nii.gz -o {mask_dir}/sub-{subject_id}_wm_gnc.nii.gz -interp nn"

        for cmd in [dwiextract_cmd, dwidenoise_cmd, hhl_gnc_sigma_cmd, hhl_gnc_mask_cmd, hhl_gnc_wm_cmd]:
            execute_command_and_log_output(cmd, f"Command '{cmd.split()[0]}' executed successfully for {subject_id}.", subject_id)

def append_all_commands_to_script():
    subject_id = subj_entry.get("1.0", 'end-1c').strip()
    base_dir = subj_process_dir_entry.get("1.0", 'end-1c').strip()
    subject = 'sub-' + subject_id

    # Ensure the script directory exists
    script_dir = f"{base_dir}/s0_script"
    os.makedirs(script_dir, exist_ok=True)

    # Commands for each step
    # 1. DCM2BIDS
    dcm2bids_cmd = dcm2bids_command(subject_id, bidspath_entry.get("1.0", 'end-1c').strip(), config_entry.get("1.0", 'end-1c').strip(), dcm_source_entry.get("1.0", 'end-1c').strip())
    append_command_to_script(dcm2bids_cmd, base_dir, subject)

    # 2. Export Diffusion Parameters
    export_diffusion_params_cmd = export_diffusion_parameters_command(subject_id, subj_raw_dir_entry.get("1.0", 'end-1c').strip())
    append_command_to_script(export_diffusion_params_cmd, base_dir, subject)

    # 3. Concatenate DWI Data
    concatenate_dwi_data_cmd = concatenate_dwi_data_command(subj_raw_dir_entry.get("1.0", 'end-1c').strip(), subject, base_dir)
    append_command_to_script(concatenate_dwi_data_cmd, base_dir, subject)

    # 4. Denoise (if applicable)
    denoise_option_value = denoise_option.get()
    if denoise_option_value != "no_denoise":
        denoise_cmd = denoise_commands(subject, base_dir, denoise_option_value)
        append_command_to_script(denoise_cmd, base_dir, subject)

    # 5. Degibbs
    degibbs_cmd = degibbs_commands(subject, base_dir, selected_flow.get())
    append_command_to_script(degibbs_cmd, base_dir, subject)

    # 6. TopUp
    # Get PA and AP volume indices from GUI
    pa_volume_str = pa_volume_entry.get("1.0", "end-1c").strip()
    ap_volume_str = ap_volume_entry.get("1.0", "end-1c").strip()
    
    # Convert to int with default values
    try:
        pa_volume_index = int(pa_volume_str) if pa_volume_str else 0
    except ValueError:
        pa_volume_index = 0
    
    try:
        ap_volume_index = int(ap_volume_str) if ap_volume_str else 0
    except ValueError:
        ap_volume_index = 0
    
    topup_cmds = topup_commands(base_dir, subject, selected_flow.get(), pa_volume_index, ap_volume_index)
    for cmd in topup_cmds:
        append_command_to_script(cmd, base_dir, subject)

    # 7. Generate Masks
    generate_masks_cmds, _ = generate_masks_commands(subject, base_dir, selected_flow.get())
    for cmd in generate_masks_cmds:
        append_command_to_script(cmd, base_dir, subject)

    # 8. Eddy
    eddy_cmd = eddy_commands(subject, base_dir, selected_flow.get())
    append_command_to_script(eddy_cmd, base_dir, subject)

    # 9. GNC DWI
    gnc_cmd = gnc_commands(subject, base_dir, selected_flow.get(), gnc_option.get())
    append_command_to_script(gnc_cmd, base_dir, subject)

    # 10. GNC Anat
    gnc_anat_cmd = gnc_anat_commands(subject, anat_process_dir_entry.get("1.0", 'end-1c').strip(), image_to_run_gnc_dir_entry.get("1.0", 'end-1c').strip(), gnc_anat_option.get())
    append_command_to_script(gnc_anat_cmd, base_dir, subject)

    # 11. recon-all
    expertFile = "/your/project/directory/bids/code/preprocessing_dwi/helpers/recon/expertFile"
    fsInput = fsInput_entry.get("1.0", 'end-1c').strip()
    recon_all_cmd = f"export SUBJECTS_DIR={base_dir}; recon-all -subjid fs -i {fsInput} -all -hires -expert {expertFile}"
    append_command_to_script(recon_all_cmd, base_dir, subject)

    # 12. MPPCA Noise Map Generation
    subject_id = subj_entry.get("1.0", 'end-1c').strip()
    base_dir = subj_process_dir_entry.get("1.0", 'end-1c').strip()
    concat_dir = f"{base_dir}/s1_concat"
    selected_flow_value = selected_flow.get()
    
    # Determine folder suffixes based on selected flow
    noise_dir_suffix = "s9_denoise_degibbs_noise" if selected_flow_value == "concat_denoise_degibbs" else "s9_noise"
    mask_dir_suffix = "s5_denoise_degibbs_mask" if selected_flow_value == "concat_denoise_degibbs" else "s5_mask"
    
    # Set scanner-specific GNC command
    if gnc_option.get() == "C2":
        hhl_gnc_cmd = "gncunwarp.sh -i {base_dir}/{eddy_dir_suffix}/sub-{subject_id}_dwi_eddy.nii.gz -o {base_dir}/{gnc_dir_suffix}/sub-{subject_id}_dwi.nii.gz -g /your/project/directory/bids/code/preprocessing_dwi/gradnonlinunwarp/gradient_coefficients/coeff.grad"

    # Commands for MPPCA_noise
    dwiextract_cmd = f"dwiextract {concat_dir}/*dwi.nii.gz -fslgrad {concat_dir}/*bvec {concat_dir}/*bval -bzero {concat_dir}/sub-{subject_id}_b0s.nii.gz"
    dwidenoise_cmd = f"dwidenoise {concat_dir}/sub-{subject_id}_b0s.nii.gz {concat_dir}/sub-{subject_id}_b0s_denoised.nii.gz -noise {concat_dir}/sub-{subject_id}_sigma.nii.gz"
    hcps_gnc_sigma_cmd = f"{hcps_gnc_cmd} -i {concat_dir}/sub-{subject_id}_sigma.nii.gz -o {base_dir}/{noise_dir_suffix}/sub-{subject_id}_sigma.nii.gz -interp spline"
    
    mask_dir = f"{base_dir}/{mask_dir_suffix}"
    hcps_gnc_mask_cmd = f"{hcps_gnc_cmd} -i {mask_dir}/brain_mask.nii.gz -o {mask_dir}/sub-{subject_id}_brain_mask_gnc.nii.gz -interp nn"
    hcps_gnc_wm_cmd = f"{hcps_gnc_cmd} -i {mask_dir}/wm.nii.gz -o {mask_dir}/sub-{subject_id}_wm_gnc.nii.gz -interp nn"

    # Append commands to script
    for cmd in [dwiextract_cmd, dwidenoise_cmd, hcps_gnc_c2_cmd, hcps_gnc_mask_cmd,hcps_gnc_wm_cmd]:
        append_command_to_script(cmd, base_dir, subject)

    msgbox.showinfo("Success", "All commands appended successfully to the script.")

def write_output_to_processed_dwi():
    # Fetch a list of subject IDs
    subject_ids = get_subject_ids()
    selected_flow_value = selected_flow.get()

    for subject_id in subject_ids:
        subj_id = f"sub-{subject_id}"
        source_base_dir = f"/your/project/directory/bids/sub-{subject_id}"
        destination_dir = f"/your/project/directory/bids/derivatives/processed_dwi/{subj_id}"
        freesurfer_destination_dir = f"/your/project/directory/bids/derivatives/FreeSurfer/{subj_id}"

        # Create destination directories if they do not exist
        os.makedirs(destination_dir, exist_ok=True)
        os.makedirs(freesurfer_destination_dir, exist_ok=True)

        # Determine folder suffixes based on selected flow
        if selected_flow_value == "concat_denoise_degibbs":
            eddy_pattern = "s6_denoise_degibbs_eddy/*rotated_bvecs"
            final_pattern = "s8_denoise_degibbs_final/*_dwi.nii.gz"
            noise_pattern = "s9_denoise_degibbs_noise/*_sigma.nii.gz"
        else:
            eddy_pattern = "s6_degibbs_eddy/*rotated_bvecs"
            final_pattern = "s8_final/*_dwi.nii.gz"
            noise_pattern = "s9_noise/*_sigma.nii.gz"

        # Files to be copied for processed DWI
        file_patterns = {
            "s1_concat/*.bval_mod": f"{subj_id}.bval",
            "s1_concat/*.phaseEncoding": f"{subj_id}.phaseEncoding",
            "s1_concat/*.pulseWidth": f"{subj_id}.pulseWidth",
            "s1_concat/*.diffusionTime": f"{subj_id}.diffusionTime",
            eddy_pattern: f"{subj_id}.bvec",
            final_pattern: f"{subj_id}_dwi.nii.gz",
            noise_pattern: f"{subj_id}_sigma.nii.gz"
        }

        # Copy the files for processed DWI
        try:
            for pattern, output_name in file_patterns.items():
                file_pattern = os.path.join(source_base_dir, "dwi_process", pattern)
                files_found = glob.glob(file_pattern)
                if not files_found:
                    status_text.insert('end', f"No files found for pattern: {file_pattern}\n")
                    continue

                for file_path in files_found:
                    # Determine the destination path
                    destination_file_path = os.path.join(destination_dir, output_name)

                    # Copy the file
                    shutil.copy(file_path, destination_file_path)
                    status_text.insert('end', f"Copied to: {destination_file_path}\n")
        except Exception as e:
            status_text.insert('end', f"An error occurred for {subj_id}: {e}\n")

        # Move to the correct directory and set up environment variables for FreeSurfer
        env_exports = f"""
        export FREESURFER_HOME=/usr/local/freesurfer/8.0.0
        export FSFAST_HOME=/usr/local/freesurfer/8.0.0/fsfast
        export SUBJECTS_DIR=/usr/local/freesurfer/8.0.0/subjects
        export MNI_DIR=/usr/local/freesurfer/8.0.0/mni
        source $FREESURFER_HOME/SetUpFreeSurfer.sh
        cd {destination_dir}
        """

        # Define the processing commands
        commands = [
            f"dwiextract {subj_id}_dwi.nii.gz -fslgrad {subj_id}.bvec {subj_id}.bval -bzero b0s.nii.gz -force",
            "mrmath b0s.nii.gz mean -axis 3 b0s_mean.nii.gz -force",
            "mri_synthseg --i b0s_mean.nii.gz --o b0s_topup_mean_synthseg.nii.gz",
            "mrcalc b0s_topup_mean_synthseg.nii.gz 2 -eq b0s_topup_mean_synthseg.nii.gz 41 -eq -add wm_temp.nii.gz -force",
            f"mrgrid wm_temp.nii.gz regrid -template b0s_mean.nii.gz {subj_id}_wm_mask.nii.gz -interp nearest -force",
            "mrcalc b0s_topup_mean_synthseg.nii.gz 0 -gt brain_mask_temp.nii.gz -force",
            f"mrgrid brain_mask_temp.nii.gz regrid -template b0s_mean.nii.gz {subj_id}_brain_mask.nii.gz -interp nearest -force",
            "rm b0s*",
            "rm brain_mask*",
            "rm wm*"
        ]

        # Execute the commands with the environment setup
        execute_commands_with_env(commands, env_exports, f"Processed DWI and masks created successfully for {subj_id}.", subject_id)

        # Copy the FreeSurfer data
        freesurfer_source_dir = os.path.join(source_base_dir, "anat_process/fs8")
        if os.path.exists(freesurfer_source_dir):
            try:
                # Copy the entire FreeSurfer directory for the subject
                dest_fs_dir = os.path.join(freesurfer_destination_dir, "fs")
                if os.path.exists(dest_fs_dir):
                    shutil.rmtree(dest_fs_dir)  # Remove existing FreeSurfer directory if present
                shutil.copytree(freesurfer_source_dir, dest_fs_dir)
                status_text.insert('end', f"Copied FreeSurfer data to: {dest_fs_dir}\n")
            except Exception as e:
                status_text.insert('end', f"An error occurred while copying FreeSurfer data for {subj_id}: {e}\n")
        else:
            status_text.insert('end', f"FreeSurfer source directory does not exist for {subj_id}: {freesurfer_source_dir}\n")

        status_text.see('end')


def read_file(file_path):
    """
    Reads a file and returns a list of values, splitting by both spaces and newlines.
    """
    with open(file_path, 'r') as file:
        # Read the file content and split by both lines and spaces
        values = []
        for line in file:
            values.extend(line.strip().split())  # Strip newline and split by space
        return values


def find_indices(phase_encoding_file, diffusion_time_file, bval_file, scanner_type):
    """
    Finds the indices based on phase encoding, diffusion time, and b-values.
    """
    phase_encodings = read_file(phase_encoding_file)
    diffusion_times = read_file(diffusion_time_file)
    bvals = read_file(bval_file)
    
    # Debug: print out the first few entries
    for i, (pe, dt, bv) in enumerate(zip(phase_encodings, diffusion_times, bvals)):
        if i < 10:  # print the first 10 to check
            print(f"PE: {pe}, DT: {dt}, BV: {bv}")

    # Diffusion time criteria based on scanner type
    if scanner_type == "C2":
        diff_time_a = "30"
        diff_time_b = "13"
    else:
        raise ValueError("Scanner parameters unknown.")

    # Indices for different categories
    indices_b0s_PA = [i for i, pe in enumerate(phase_encodings) if pe == "-1"]
    indices_difftimea_ms = [i for i, (pe, dt) in enumerate(zip(phase_encodings, diffusion_times)) if pe == "1" and dt == diff_time_a]
    indices_difftimeb_ms = [i for i, (pe, dt) in enumerate(zip(phase_encodings, diffusion_times)) if pe == "1" and dt == diff_time_b]
    
    indices_difftimea_b2400_less = [i for i, (pe, dt, bv) in enumerate(zip(phase_encodings, diffusion_times, bvals)) if pe == "1" and dt == diff_time_a and 0 < float(bv) < 2400]
    indices_difftimea_b2400_greater = [i for i, (pe, dt, bv) in enumerate(zip(phase_encodings, diffusion_times, bvals)) if pe == "1" and dt == diff_time_a and float(bv) >= 2400]
    indices_difftimeb_b2400_less = [i for i, (pe, dt, bv) in enumerate(zip(phase_encodings, diffusion_times, bvals)) if pe == "1" and dt == diff_time_b and 0 < float(bv) < 2400]
    indices_difftimeb_b2400_greater = [i for i, (pe, dt, bv) in enumerate(zip(phase_encodings, diffusion_times, bvals)) if pe == "1" and dt == diff_time_b and float(bv) >= 2400]

    # Debug: Print out the length of indices
    print(f"Indices for b0s PA ({scanner_type}):", len(indices_b0s_PA))
    print(f"Indices for DT={diff_time_a}ms ({scanner_type}):", len(indices_difftimea_ms))
    print(f"Indices for DT={diff_time_b}ms ({scanner_type}):", len(indices_difftimeb_ms))
    print(f"Indices for DT={diff_time_a}, BV<2400 ({scanner_type}):", len(indices_difftimea_b2400_less))
    print(f"Indices for DT={diff_time_a}, BV>=2400 ({scanner_type}):", len(indices_difftimea_b2400_greater))
    print(f"Indices for DT={diff_time_b}, BV<2400 ({scanner_type}):", len(indices_difftimeb_b2400_less))
    print(f"Indices for DT={diff_time_b}, BV>=2400 ({scanner_type}):", len(indices_difftimeb_b2400_greater))

    return (
        indices_b0s_PA, 
        indices_difftimea_ms, 
        indices_difftimeb_ms,
        indices_difftimea_b2400_less, 
        indices_difftimea_b2400_greater, 
        indices_difftimeb_b2400_less, 
        indices_difftimeb_b2400_greater
    )


def run_mrconvert(input_file, bvec_file, bval_file, indices, output_file, output_bvec_file, output_bval_file, subject_id, folder_name):
    """
    Runs the mrconvert command to process DWI volumes based on the specified indices.
    """
    base_dir = bidspath_entry.get("1.0", "end-1c").strip()  # Dynamically get the base path from the BIDS path entry
    output_dir = f"{base_dir}/{subject_id}/dwi_process/{folder_name}"
    os.makedirs(output_dir, exist_ok=True)

    full_output_file = f"{output_dir}/{output_file}"
    full_output_bvec_file = f"{output_dir}/{output_bvec_file}"
    full_output_bval_file = f"{output_dir}/{output_bval_file}"

    if indices:
        index_range = ",".join(map(str, indices))  # Use specific indices instead of a range
    else:
        status_text.insert('end', f"No indices provided for {subject_id}.\n")
        return

    command = [
        "mrconvert", input_file,
        "-fslgrad", bvec_file, bval_file,
        "-coord", "3", index_range,
        full_output_file,
        "-export_grad_fsl", full_output_bvec_file, full_output_bval_file,
        "-force"
    ]
    
    # Convert command list to string
    cmd_str = " ".join(command)
    
    # Append command to script
    base_dir_dwi = f"{base_dir}/{subject_id}/dwi_process"
    subject = subject_id
    append_command_to_script(cmd_str, base_dir_dwi, subject)
    
    try:
        # Execute the mrconvert command
        subprocess.run(command, check=True)
        status_text.insert('end', f"mrconvert executed successfully for {subject_id}. Output saved to {output_dir}.\n")
    except subprocess.CalledProcessError as e:
        status_text.insert('end', f"Error running mrconvert for {subject_id}: {e.stderr}\n")
    status_text.see('end')

def execute_sandi_volume_division():
    """
    Executes the DWI volume processing for SANDI.
    """
    subject_ids = get_subject_ids()
    scanner_type = "C2"

    for subject_id in subject_ids:
        subj_id = f"sub-{subject_id}"
        base_dir = bidspath_entry.get("1.0", "end-1c").strip()

        input_file = f'/your/project/directory/bids/derivatives/processed_dwi/{subj_id}/{subj_id}_dwi.nii.gz'
        phase_encoding_file = f'/your/project/directory/bids/derivatives/processed_dwi/{subj_id}/{subj_id}.phaseEncoding'
        diffusion_time_file = f'/your/project/directory/bids/derivatives/processed_dwi/{subj_id}/{subj_id}.diffusionTime'
        bval_file = f'/your/project/directory/bids/derivatives/processed_dwi/{subj_id}/{subj_id}.bval'
        bvec_file = f'/your/project/directory/bids/derivatives/processed_dwi/{subj_id}/{subj_id}.bvec'

        try:
            indices_b0s_PA, indices_difftimea_ms, indices_difftimeb_ms, _, _, _, _ = find_indices(
                phase_encoding_file, diffusion_time_file, bval_file, scanner_type
            )

            run_mrconvert(input_file, bvec_file, bval_file, indices_b0s_PA, "b0s_PA.nii.gz", "bvecs_b0s_PA.txt", "bvals_b0s_PA.txt", subj_id, "s13_SANDI")
            run_mrconvert(input_file, bvec_file, bval_file, indices_difftimea_ms, "difftimea_ms.nii.gz", "bvecs_difftimea_ms.txt", "bvals_difftimea_ms.txt", subj_id, "s13_SANDI")
            run_mrconvert(input_file, bvec_file, bval_file, indices_difftimeb_ms, "difftimeb_ms.nii.gz", "bvecs_difftimeb_ms.txt", "bvals_difftimeb_ms.txt", subj_id, "s13_SANDI")

            status_text.insert('end', f"SANDI volume processing completed successfully for {subj_id}.\n")
        except Exception as e:
            status_text.insert('end', f"An error occurred for {subj_id}: {e}\n")
        status_text.see('end')


def execute_tractcaliber_volume_division():
    """
    Executes the DWI volume processing for TractCaliber based on scanner type.
    """
    subject_ids = get_subject_ids()
    scanner_type = "C2"

    for subject_id in subject_ids:
        subj_id = f"sub-{subject_id}"
        base_dir = bidspath_entry.get("1.0", "end-1c").strip()

        input_file = f'/your/project/directory/bids/derivatives/processed_dwi/{subj_id}/{subj_id}_dwi.nii.gz'
        phase_encoding_file = f'/your/project/directory/bids/derivatives/processed_dwi/{subj_id}/{subj_id}.phaseEncoding'
        diffusion_time_file = f'/your/project/directory/bids/derivatives/processed_dwi/{subj_id}/{subj_id}.diffusionTime'
        bval_file = f'/your/project/directory/bids/derivatives/processed_dwi/{subj_id}/{subj_id}.bval'
        bvec_file = f'/your/project/directory/bids/derivatives/processed_dwi/{subj_id}/{subj_id}.bvec'

        try:
            indices_b0s_PA, _, _, indices_difftimea_b2400_less, indices_difftimea_b2400_greater, indices_difftimeb_b2400_less, indices_difftimeb_b2400_greater = find_indices(
                phase_encoding_file, diffusion_time_file, bval_file, scanner_type
            )

            run_mrconvert(input_file, bvec_file, bval_file, range(min(indices_b0s_PA), max(indices_b0s_PA)+1), "b0s_PA.nii.gz", "bvecs_b0s_PA.txt", "bvals_b0s_PA.txt", subj_id, "s10_TractCaliber")
            run_mrconvert(input_file, bvec_file, bval_file, range(min(indices_difftimea_b2400_less)-1,max(indices_difftimea_b2400_less)+1), "qb32_difftimea_ms.nii.gz", "bvecs_qb32_difftimea_ms.txt", "bvals_qb32_difftimea_ms.txt", subj_id, "s10_TractCaliber")
            run_mrconvert(input_file, bvec_file, bval_file, range(min(indices_difftimea_b2400_greater)-1,max(indices_difftimea_b2400_greater)+1), "qb64_difftimea_ms.nii.gz", "bvecs_qb64_difftimea_ms.txt", "bvals_qb64_difftimea_ms.txt", subj_id, "s10_TractCaliber")
            run_mrconvert(input_file, bvec_file, bval_file, range(min(indices_difftimeb_b2400_less)-1,max(indices_difftimeb_b2400_less)+1), "qb32_difftimeb_ms.nii.gz", "bvecs_qb32_difftimeb_ms.txt", "bvals_qb32_difftimeb_ms.txt", subj_id, "s10_TractCaliber")
            run_mrconvert(input_file, bvec_file, bval_file, range(min(indices_difftimeb_b2400_greater)-1,max(indices_difftimeb_b2400_greater)+1), "qb64_difftimeb_ms.nii.gz", "bvecs_qb64_difftimeb_ms.txt", "bvals_qb64_difftimeb_ms.txt", subj_id, "s10_TractCaliber")

            status_text.insert('end', f"TractCaliber volume processing completed successfully for {subj_id}.\n")
        except Exception as e:
            status_text.insert('end', f"An error occurred for {subj_id}: {e}\n")
        status_text.see('end')



def run_tractseg_for_subject(subject_id):
    """
    Executes the TractSeg pipeline steps directly in Python for a specific subject.
    """
    base_dir = bidspath_entry.get("1.0", "end-1c").strip()  # Dynamically get the base path from the entry
    dwi_dir = f"{base_dir}/sub-{subject_id}/dwi_process/s13_SANDI"
    output_dir = f"/your/project/directory/bids/derivatives/TractSeg_v1/sub-{subject_id}/"

    dwi_nii = f"{dwi_dir}/difftimeb_ms.nii.gz"
    bval_txt = f"{dwi_dir}/bvals_difftimeb_ms.txt"
    bvec_txt = f"{dwi_dir}/bvecs_difftimeb_ms.txt"
    mask_nii = f"/your/project/directory/bids/derivatives/processed_dwi/sub-{subject_id}/sub-{subject_id}_brain_mask.nii.gz"

    
    try:
        # Step 1: Generate PEAKS and binary tract segmentation maps
        tractseg_command = f"""
        {env_activate_command} && \
        TractSeg -i {dwi_nii} --brain_mask {mask_nii} -o {tractseg_out_dir} \
        --raw_diffusion_input --csd_type csd_msmt --bvals {bval_txt} --bvecs {bvec_txt} \
        --keep_intermediate_files --output_type tract_segmentation
        """
        # Append command to script
        base_dir_dwi = f"{base_dir}/sub-{subject_id}/dwi_process"
        subject = f"sub-{subject_id}"
        append_command_to_script(tractseg_command.strip(), base_dir_dwi, subject)
        subprocess.run(tractseg_command, shell=True, check=True)

        # Step 2: Generate tract end ROIs
        tract_endings_command = f"""
        {env_activate_command} && \
        TractSeg -i {tractseg_out_dir}peaks.nii.gz -o {tractseg_out_dir} --output_type endings_segmentation
        """
        append_command_to_script(tract_endings_command.strip(), base_dir_dwi, subject)
        subprocess.run(tract_endings_command, shell=True, check=True)

        # Step 3: Generate tract-orientation maps (TOM)
        tom_command = f"""
        {env_activate_command} && \
        TractSeg -i {tractseg_out_dir}peaks.nii.gz -o {tractseg_out_dir} --output_type TOM
        """
        append_command_to_script(tom_command.strip(), base_dir_dwi, subject)
        subprocess.run(tom_command, shell=True, check=True)

        # Step 4: Perform tractography within tract-masks
        tracking_command = f"""
        {env_activate_command} && \
        Tracking -i {tractseg_out_dir}peaks.nii.gz -o {tractseg_out_dir} --tracking_format tck --nr_fibers 2000
        """
        append_command_to_script(tracking_command.strip(), base_dir_dwi, subject)
        subprocess.run(tracking_command, shell=True, check=True)

        status_text.insert('end', f"TractSeg processing for {subject_id} completed successfully.\n")

    except subprocess.CalledProcessError as e:
        status_text.insert('end', f"An error occurred while running TractSeg for {subject_id}: {e.stderr}\n")
    finally:
        status_text.see('end')  # Auto-scroll to the end


def run_tractseg_for_all_subjects():
    """
    Fetches multiple subject IDs from the GUI and runs TractSeg for each subject.
    """
    subject_ids = get_subject_ids()  # Fetches all subject IDs from the subject entry widget

    for subject_id in subject_ids:
        run_tractseg_for_subject(subject_id)  # Run TractSeg for each subject

    
def execute_all_steps():
    """
    Sequentially executes all the processing steps, waiting for each to complete before proceeding.
    """
    def check_dwi_file_entries():
        """Check if any of the DWI file entries contains a valid path."""
        for entry in dwi_file_entries:
            if entry.get("1.0", 'end-1c').strip():  # Check if any entry is not empty
                return True
        return False
    
    def run_step(step_function, next_steps):
        try:
            step_function()  # Execute the step
            if next_steps:  # If there are more steps, proceed with the next one
                root.after(100, run_step, next_steps[0], next_steps[1:])
            else:
                msgbox.showinfo("Success", "All selected steps executed successfully.")
        except Exception as e:
            msgbox.showerror("Error", f"An error occurred during processing: {str(e)}")

    # Determine which concatenate DWI step to include
    if check_dwi_file_entries():
        concatenate_step = concatenate_dwi_data_from_gui_entries
    else:
        concatenate_step = execute_concatenate_dwi_data
    
    # Build the steps list dynamically based on checkbox selections
    steps = []
    
    if step_dcm2bids.get():
        steps.append(execute_dcm2bids)
    
    if step_export_params.get():
        steps.append(execute_export_diffusion_parameters)
    
    if step_concatenate.get():
        steps.append(concatenate_step)  # Use the chosen concatenate function
    
    # Add denoise step if checkbox is selected AND denoise option is not "no_denoise"
    denoise_option_value = denoise_option.get()
    selected_flow_value = selected_flow.get()
    
    if step_denoise.get() and (selected_flow_value == "concat_denoise_degibbs" or denoise_option_value != "no_denoise"):
        steps.append(execute_denoise)
    
    # Continue with remaining steps based on checkboxes
    if step_degibbs.get():
        steps.append(execute_degibbs)
    
    if step_topup.get():
        steps.append(execute_topup)
    
    if step_masks.get():
        steps.append(execute_generate_masks)
    
    if step_eddy.get():
        steps.append(execute_eddy)
    
    if step_gnc.get():
        steps.append(execute_gnc_dwi)
    
    if step_interpolation.get():
        steps.append(execute_interpolation_eddy_gnc)
    
    if step_MPPCA_noise.get():
        steps.append(MPPCA_noise)
    
    if step_write_output.get():
        steps.append(write_output_to_processed_dwi)

    if step_gnc_anat.get():
        steps.append(execute_gnc_anat)
    
    if step_recon_all.get():
        steps.append(execute_recon_all)
    
    if step_sandi_division.get():
        steps.append(execute_sandi_volume_division)
    
    if step_tractcaliber.get():
        steps.append(execute_tractcaliber_volume_division)
    
    if step_tractseg.get():
        steps.append(run_tractseg_for_all_subjects)
    
    if steps:
        run_step(steps[0], steps[1:])
    else:
        msgbox.showwarning("No steps selected", "Please select at least one processing step.")


# Function to create a horizontal scrollable entry field with copy/paste functionality
def make_horizontal_scrollable_entry(parent, width, height):
    entry_frame = ttk.Frame(parent)
    entry = tk.Text(entry_frame, width=width, height=height, wrap='none', undo=True)
    scrollbar_x = ttk.Scrollbar(entry_frame, command=entry.xview, orient="horizontal", style='Thin.Horizontal.TScrollbar')
    entry.config(xscrollcommand=scrollbar_x.set)
    entry.grid(row=0, column=0, sticky="nsew")
    entry_frame.columnconfigure(0, weight=1)  # Make the entry expand
    scrollbar_x.grid(row=1, column=0, sticky="ew")
    
    # Right-click context menu
    menu = tk.Menu(entry, tearoff=0)
    menu.add_command(label="Cut", command=lambda: entry.event_generate("<<Cut>>"))
    menu.add_command(label="Copy", command=lambda: entry.event_generate("<<Copy>>"))
    menu.add_command(label="Paste", command=lambda: entry.event_generate("<<Paste>>"))
    
    def show_context_menu(event):
        menu.post(event.x_root, event.y_root)
        
    entry.bind("<Button-3>", show_context_menu)
    return entry, entry_frame

# Create the main window
root = tk.Tk()
root.title("Connectome 2.0 Diffusion Pre-Processing")

# Create a canvas and a scrollbar
canvas = tk.Canvas(root)
canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

scrollbar = ttk.Scrollbar(root, orient="vertical", command=canvas.yview)
scrollbar.pack(side=tk.RIGHT, fill="y")

canvas.configure(yscrollcommand=scrollbar.set)

# Create a frame inside the canvas
main_frame = ttk.Frame(canvas)

# Add the main_frame to the canvas
canvas.create_window((0, 0), window=main_frame, anchor="nw")

def on_frame_configure(event=None):
    # Update the scrollable size of the canvas
    canvas.configure(scrollregion=canvas.bbox("all"))

def on_mousewheel(event):
    # Allow scrolling with the mouse wheel
    canvas.yview_scroll(int(-1*(event.delta/120)), "units")

main_frame.bind("<Configure>", on_frame_configure)
canvas.bind_all("<MouseWheel>", on_mousewheel)  # This might need adjustment on Linux or macOS

# Style configuration
style = ttk.Style()
style.theme_use('clam')

# Set default font
default_font = ('Arial', 8)
root.option_add('*Font', default_font)

# Configure style for the large buttons
button_style = ttk.Style()
button_style.configure('Large.TButton', font=('Arial', 8, 'bold'), background='white')
button_style = ttk.Style()
button_style.configure('Small.TButton', font=('Arial', 8))

# Configure style for the thinner horizontal scrollbar
style.configure('Thin.Horizontal.TScrollbar', gripcount=0, borderwidth=1, arrowcolor='blue')

row_num=0

# Subject ID Entry
tk.Label(main_frame, text="Subject ID:").grid(row=row_num, column=0, sticky='w')
subj_entry, subj_entry_frame = make_horizontal_scrollable_entry(main_frame, width=50, height=1)
subj_entry_frame.grid(row=row_num, column=1, sticky='ew')
subj_entry.insert('1.0', "000")
# Bind the key release event to the subj_entry widget
subj_entry.bind("<KeyRelease>", on_key_release)

# BIDS Path Entry
tk.Label(main_frame, text="BIDS path:").grid(row=(row_num := row_num + 1), column=0, sticky='w')
bidspath_entry, bidspath_entry_frame = make_horizontal_scrollable_entry(main_frame, width=50, height=1)
bidspath_entry_frame.grid(row=row_num, column=1, sticky='ew')
bidspath_entry.insert('1.0', "/your/project/directory/bids")
# Bind the key release event to the bidspath_entry widget
bidspath_entry.bind("<KeyRelease>", lambda event: update_paths())


# Config Path Entry
tk.Label(main_frame, text="Configuration file path:").grid(row=(row_num := row_num + 1), column=0, sticky='w')
config_entry, config_entry_frame = make_horizontal_scrollable_entry(main_frame, width=50, height=1)
config_entry_frame.grid(row=row_num, column=1, sticky='ew')
config_entry.insert('1.0', "/your/project/directory/bids/code/preprocessing_dwi/helpers/dcm2bids/config.json")

# DICOM Source Entry
tk.Label(main_frame, text="Path to DICOM files:").grid(row=(row_num := row_num + 1), column=0, sticky='w')
dcm_source_entry, dcm_source_entry_frame = make_horizontal_scrollable_entry(main_frame, width=50, height=1)
dcm_source_entry_frame.grid(row=row_num, column=1, sticky='ew')
dcm_source_entry.insert('1.0', "")

execute_dcm2bids_button = ttk.Button(main_frame, text="Execute dcm2bids", command=execute_dcm2bids, style='Large.TButton', width=30)
execute_dcm2bids_button.grid(row=(row_num := row_num + 1), column=1, padx=(10, 0))

# Separator after dcm2bids section
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")

# Subj Raw Directory Entry
tk.Label(main_frame, text="Subject raw directory:").grid(row=(row_num := row_num + 1), column=0, sticky='w')
subj_raw_dir_entry, subj_raw_dir_entry_frame = make_horizontal_scrollable_entry(main_frame, width=50, height=1)
subj_raw_dir_entry_frame.grid(row=row_num, column=1, sticky='ew')
subj_raw_dir_entry.insert('1.0', "/your/project/directory/bids/sub-000/dwi")

execute_export_diffusion_parameters_button = ttk.Button(main_frame, 
                                                        text="Export diffusion parameters", 
                                                        command=execute_export_diffusion_parameters, 
                                                        style='Large.TButton', width=30)
execute_export_diffusion_parameters_button.grid(row=(row_num := row_num + 1), column=1, padx=(10, 0))

# Separator after diffusion parameters section
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")

# Subj Processing Directory Entry
tk.Label(main_frame, text="DWI processing directory:").grid(row=(row_num := row_num + 1), column=0, sticky='w')
subj_process_dir_entry, subj_process_dir_entry_frame = make_horizontal_scrollable_entry(main_frame, width=50, height=1)
subj_process_dir_entry_frame.grid(row=row_num, column=1, sticky='ew')
subj_process_dir_entry.insert('1.0', "/your/project/directory/bids/sub-000/dwi_process")

def create_file_entry_widgets(parent):
    """Create entry widgets for DWI file paths and the output folder, with a button to open a file dialog."""
    dwi_file_labels = ["DWI file #1 (PA):", "DWI file #2 (PA+1):", "DWI file #3 (PA-1):", "DWI file #4 (PA+2):", "DWI file #5 (PA+3):"]
    dwi_file_entries = []
    global row_num
    for i, label in enumerate(dwi_file_labels, start=(row_num := row_num + 1)):  # Adjust start index based on your layout
        # Create a row frame
        row_frame = ttk.Frame(parent)
        row_frame.grid(row=i, column=1, sticky='ew', padx=5)
        parent.columnconfigure(1, weight=1)
        row_frame.columnconfigure(0, weight=4)
        
        tk.Label(parent, text=label).grid(row=i, column=0, sticky='w', padx=5, pady=2)
        
        # Create entry with scrollable functionality
        entry, entry_frame = make_horizontal_scrollable_entry(row_frame, width=40, height=1)
        entry_frame.grid(row=0, column=0, sticky='ew', padx=(0, 5))
        
        # Button to open file dialog
        def open_file_dialog(entry=entry):
            # Retrieve the subject ID from the subject ID entry widget
            subject_id = subj_entry.get("1.0", 'end-1c').strip()
            initial_directory = f"/your/project/directory/bids/sub-{subject_id}/dwi"
            
            # Define the function to open the file dialog and update the entry
            filename = filedialog.askopenfilename(
                initialdir=initial_directory,  # Use the dynamic initial directory based on subject ID
                title="Select file",
                filetypes=(("Nifti files", "*.nii *.nii.gz"), ("all files", "*.*")))
            entry.delete("1.0", 'end')
            entry.insert("1.0", filename)
        
        # Add button next to the entry
        browse_button = ttk.Button(row_frame, text="Browse", command=lambda e=entry: open_file_dialog(e))
        browse_button.grid(row=0, column=1, sticky='ew')
        
        dwi_file_entries.append(entry)
    
    return dwi_file_entries


dwi_file_entries = create_file_entry_widgets(main_frame)

concatenate_dwi_button = ttk.Button(main_frame, text="Concat DWI data w/ manual entries", command=concatenate_dwi_data_from_gui_entries,style='Large.TButton',width=30)
concatenate_dwi_button.grid(row=(row_num := row_num + 5), column=1, padx=(10,0))  # Adjust the row and column indices appropriately

execute_concatenate_dwi_data_button = ttk.Button(main_frame, text="Concatenate DWI data", command=execute_concatenate_dwi_data, style='Large.TButton', width=30)
execute_concatenate_dwi_data_button.grid(row=(row_num := row_num + 1), column=1, padx=(10, 0))

# Separator after concatenation section
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")

# Denoise Option Selection
tk.Label(main_frame, text="Select denoise option:").grid(row=(row_num := row_num + 1), column=0, sticky='w')
denoise_option = tk.StringVar(value="no_denoise")

# Internal frame for denoise radio buttons
denoise_radio_button_frame = tk.Frame(main_frame)  
denoise_radio_button_frame.grid(row=row_num, column=1, sticky='w')

# Radio Buttons for Denoise Option
no_denoise_rb = tk.Radiobutton(denoise_radio_button_frame, text="No denoising", variable=denoise_option, value="no_denoise", background='lightblue')
no_denoise_rb.pack(side='left', padx=5)

magnitude_denoise_rb = tk.Radiobutton(denoise_radio_button_frame, text="Magnitude denoising", variable=denoise_option, value="magnitude", background='lightblue')
magnitude_denoise_rb.pack(side='left', padx=5)

real_denoise_rb = tk.Radiobutton(denoise_radio_button_frame, text="Real denoising", variable=denoise_option, value="real", background='lightblue')
real_denoise_rb.pack(side='left', padx=5)

execute_denoise_button = ttk.Button(
    main_frame, 
    text="MP-PCA Denoise", 
    command=execute_denoise, 
    style='Large.TButton', 
    width=30
)
execute_denoise_button.grid(row=(row_num := row_num + 1), column=1, padx=(10, 0))  # Adjust the row and column as needed

# Separator after denoise section
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")

# Process Flow Selection
tk.Label(main_frame, text="Select processing flow:").grid(row=(row_num := row_num + 1), column=0, sticky='w')
selected_flow = tk.StringVar(value="concat_denoise_degibbs") # Default is denoising

# Internal frame for process flow radio buttons
radio_button_frame = tk.Frame(main_frame)
radio_button_frame.grid(row=row_num, column=1, sticky='w')

# Radio Buttons for Process Flow
rb1 = tk.Radiobutton(radio_button_frame, text="Concat → deGibbs", variable=selected_flow, value="concat_degibbs", background='lightblue')
rb1.pack(side='left', padx=5)

rb2 = tk.Radiobutton(radio_button_frame, text="Concat → denoise → deGibbs", variable=selected_flow, value="concat_denoise_degibbs", background='lightblue')
rb2.pack(side='left', padx=5)


execute_degibbs_button = ttk.Button(
    main_frame, 
    text="Gibbs ringing removal (deGibbs)", 
    command=execute_degibbs, 
    style='Large.TButton', 
    width=30
)
execute_degibbs_button.grid(row=(row_num := row_num + 1), column=1, padx=(10, 0))  # Adjust the row and column as needed

# Separator after degibbs section
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")

# Add labels and entries for PA-volume and AP-volume index:
tk.Label(main_frame, text="PA volume index:").grid(row=(row_num := row_num + 1), column=0, sticky='w')
pa_volume_entry, pa_volume_entry_frame = make_horizontal_scrollable_entry(main_frame, width=5, height=1)
pa_volume_entry_frame.grid(row=row_num, column=1, sticky='w')
pa_volume_entry.insert('1.0', "9")  # Default to 9

tk.Label(main_frame, text="AP volume index:").grid(row=(row_num := row_num + 1), column=0, sticky='w')
ap_volume_entry, ap_volume_entry_frame = make_horizontal_scrollable_entry(main_frame, width=5, height=1)
ap_volume_entry_frame.grid(row=row_num, column=1, sticky='w')
ap_volume_entry.insert('1.0', "10")  # Default to 10

# Execute TopUp Button
top_up_button = ttk.Button(main_frame, text="TopUp correction", command=execute_topup, style='Large.TButton', width=30)
top_up_button.grid(row=row_num, column=1, padx=(10, 0))

# Separator after TopUp section
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")

# Execute Generate Masks Button
execute_generate_masks_button = ttk.Button(
    main_frame, 
    text="Generate WM & brain masks", 
    command=execute_generate_masks, 
    style='Large.TButton', 
    width=30
)
execute_generate_masks_button.grid(row=(row_num := row_num + 1), column=1, padx=(10, 0))  # Adjust the row and column as needed

# Separator after Mask Generation section
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")

# Execute Eddy Button
execute_eddy_button = ttk.Button(
    main_frame, 
    text=" Eddy current correction", 
    command=execute_eddy, 
    style='Large.TButton', 
    width=30
)
execute_eddy_button.grid(row=(row_num := row_num + 1), column=1, padx=(10, 0))  # Adjust the row and column as needed

# Separator after Eddy section
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")

# Label for GNC option selection
tk.Label(main_frame, text="Select option:").grid(row=(row_num := row_num + 1), column=0, sticky='w')

# Variable to store the selected GNC option
gnc_option = tk.StringVar(value="C2")

# Internal frame for GNC option radio buttons
gnc_option_radio_button_frame = tk.Frame(main_frame)  
gnc_option_radio_button_frame.grid(row=row_num, column=1, sticky='w')

# Radio Buttons for GNC Option
gnc_c1_rb = tk.Radiobutton(gnc_option_radio_button_frame, text="Connectome 2.0 GNC", variable=gnc_option, value="C2", background='lightblue')
gnc_c1_rb.pack(side='left', padx=5)

gnc_no_gnc_rb = tk.Radiobutton(gnc_option_radio_button_frame, text="No GNC", variable=gnc_option, value="no_gnc", background='lightblue')
gnc_no_gnc_rb.pack(side='left', padx=5)

# Execute GNC DWI Button
execute_gnc_dwi_button = ttk.Button(
    main_frame,
    text="Execute GNC DWI",
    command=execute_gnc_dwi,
    style='Large.TButton',
    width=30
)
execute_gnc_dwi_button.grid(row=(row_num := row_num + 1), column=1, padx=(10, 0))


# Separator after GNC section
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")

execute_interpolation_eddy_gnc_button = ttk.Button(
    main_frame,
    text="Eddy & GNC interpolation",
    command=execute_interpolation_eddy_gnc,  # Updated to use the new function
    style='Large.TButton',
    width=30
)
execute_interpolation_eddy_gnc_button.grid(row=(row_num := row_num + 1), column=1, padx=(10, 0))


# Separator after GNC section
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")

# Button to execute MPPCA_noise
execute_MPPCA_noise_button = ttk.Button(
    main_frame, 
    text="Generate noise map from MP-PCA", 
    command=MPPCA_noise, 
    style='Large.TButton', 
    width=30
)
execute_MPPCA_noise_button.grid(row=(row_num := row_num + 1), column=1, padx=(10, 0))  # Adjust the row and column as needed
# Separator before buttons
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")

write_output_button = ttk.Button(
    main_frame, 
    text="Write output to processed_dwi", 
    command=write_output_to_processed_dwi, 
    style='Large.TButton', 
    width=30
)
write_output_button.grid(row=(row_num := row_num + 1), column=1, padx=(10, 0))  # Adjust the row and column as needed
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")

# Add a button for DWI Volume Processing
execute_dwi_volume_processing_button = ttk.Button(
    main_frame,
    text="Divide volumes for SANDI fitting",
    command=execute_sandi_volume_division,  # Set the command to the function you just defined
    style='Large.TButton',
    width=30
)
execute_dwi_volume_processing_button.grid(row=(row_num := row_num + 1), column=1, padx=(10, 0))  # Adjust the row and column as needed
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")

# Add a button for TractCaliber DWI Volume Processing
execute_tractcaliber_dwi_volume_processing_button = ttk.Button(
    main_frame,
    text="Divide vols for TractCaliber fitting",
    command=execute_tractcaliber_volume_division,  # Set the command to the function you just defined
    style='Large.TButton',
    width=30
)
execute_tractcaliber_dwi_volume_processing_button.grid(row=(row_num := row_num + 1), column=1, padx=(10, 0))  # Adjust the row and column as needed
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")

# Add the "Run TractSeg" Button to the GUI
# Button to execute TractSeg for all subjects
run_tractseg_button = ttk.Button(
    main_frame, 
    text="Run TractSeg", 
    command=run_tractseg_for_all_subjects,  # Set the new function as the command
    style='Large.TButton', 
    width=30
)
run_tractseg_button.grid(row=(row_num := row_num + 1), column=1, padx=(10, 0))  # Adjust row and column based on your layout
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")

# Anat Process Directory Entry
tk.Label(main_frame, text="Anatomical processing directory:").grid(row=(row_num := row_num + 1), column=0, sticky='w')
anat_process_dir_entry, anat_process_dir_entry_frame = make_horizontal_scrollable_entry(main_frame, width=50, height=1)
anat_process_dir_entry_frame.grid(row=row_num, column=1, sticky='ew')
anat_process_dir_entry.insert('1.0','/your/project/directory/bids/sub-000/anat_process')

# Image to Run GNC Directory Entry
tk.Label(main_frame, text="GNC anat input image:").grid(row=(row_num := row_num + 1), column=0, sticky='w')
image_to_run_gnc_dir_entry, image_to_run_gnc_dir_entry_frame = make_horizontal_scrollable_entry(main_frame, width=50, height=1)
image_to_run_gnc_dir_entry_frame.grid(row=row_num, column=1, sticky='ew')
image_to_run_gnc_dir_entry.insert('1.0','/your/project/directory/bids/sub-000/anat/sub-000_run-01_T1w.nii.gz')

# GNC Anat Option Selection
tk.Label(main_frame, text="Select option:").grid(row=(row_num := row_num + 1), column=0, sticky='w')
gnc_anat_option = tk.StringVar(value="no_gnc")  # Default value is "No GNC"

# Internal frame for GNC Anat option radio buttons
gnc_anat_radio_button_frame = tk.Frame(main_frame)  
gnc_anat_radio_button_frame.grid(row=row_num, column=1, sticky='w')

# Radio Buttons for GNC Anat Option
gnc_c2_anat_rb = tk.Radiobutton(gnc_anat_radio_button_frame, text="Connectome 2.0 GNC", variable=gnc_anat_option, value="C2", background='lightblue')
gnc_c2_anat_rb.pack(side='left', padx=5)

gnc_anat_no_gnc_rb = tk.Radiobutton(gnc_anat_radio_button_frame, text="No GNC", variable=gnc_anat_option, value="no_gnc", background='lightblue')
gnc_anat_no_gnc_rb.pack(side='left', padx=5)

# Execute GNC Anat Button
execute_gnc_anat_button = ttk.Button(
    main_frame,
    text="Execute GNC anat",
    command=execute_gnc_anat,
    style='Large.TButton',
    width=30
)
execute_gnc_anat_button.grid(row=(row_num := row_num + 1), column=1, padx=(10, 0))

# Separator before buttons
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")


# Freesurfer Input Directory Entry
tk.Label(main_frame, text="FreeSurfer segmentation input image:").grid(row=(row_num := row_num + 1), column=0, sticky='w')
fsInput_entry, fsInput_entry_frame = make_horizontal_scrollable_entry(main_frame, width=50, height=1)
fsInput_entry_frame.grid(row=row_num, column=1, sticky='ew')
fsInput_entry.insert("1.0","/your/project/directory/bids/sub-000/anat/sub-000_run-02_T1w.nii.gz")
execute_recon_all_button = ttk.Button(
    main_frame, 
    text="Execute recon-all", 
    command=execute_recon_all, 
    style='Large.TButton', 
    width=30
)
execute_recon_all_button.grid(row=(row_num := row_num + 1), column=1, padx=(10, 0))  # Adjust the row and column as needed

# Separator before buttons
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew")
row_num = row_num + 2

# Function to copy text from the status_text widget
def copy_text(event=None):
    root.clipboard_clear()
    text = status_text.get("sel.first", "sel.last")
    root.clipboard_append(text)

# Function to paste text into the status_text widget
def paste_text(event=None):
    try:
        text = root.clipboard_get()
        status_text.insert("insert", text)
    except tk.TclError:
        pass

# Frame to hold the status text and scrollbar
status_frame = ttk.Frame(main_frame)
status_frame.grid(row=0, column=2, rowspan=52, sticky='nsew', padx=5, pady=5)  # Adjust rowspan as needed

# Make the status frame expandable
main_frame.columnconfigure(2, weight=1)
main_frame.rowconfigure(0, weight=1)

# Status text widget for logs
status_text = tk.Text(status_frame, wrap='word', height=20, width=50)  # Adjust the height and width
status_text.grid(row=0, column=0, sticky='nsew')

# Scrollbar for the status text
scrollbar = ttk.Scrollbar(status_frame, orient='vertical', command=status_text.yview)
scrollbar.grid(row=0, column=1, sticky='ns')
status_text['yscrollcommand'] = scrollbar.set

# Function to display the context menu
def show_context_menu(event):
    try:
        context_menu.tk_popup(event.x_root, event.y_root)
    finally:
        context_menu.grab_release()

# Create a context menu for the status_text widget
context_menu = tk.Menu(status_text, tearoff=0)
context_menu.add_command(label="Copy", command=lambda: status_text.event_generate("<<Copy>>"))
context_menu.add_command(label="Clear", command=lambda: status_text.delete(1.0, 'end'))
status_text.bind("<Button-3>", show_context_menu)  # Bind right-click to show context menu

# Make sure the status frame expands to fill the available space
status_frame.columnconfigure(0, weight=1)
status_frame.rowconfigure(0, weight=1)

# Create a 'Clear Status' button and place it below the status_text
clear_button = ttk.Button(status_frame, text='Clear Status', command=lambda: status_text.delete(1.0, 'end'))
clear_button.grid(row=1, column=0, columnspan=2, pady=5, sticky='ew')


# Create a frame to hold the buttons
buttons_frame = ttk.Frame(main_frame)
buttons_frame.grid(row=row_num, column=0, columnspan=2, pady=(10, 0), sticky='ew')


# Button to remove the script
remove_script_button = ttk.Button(
    buttons_frame,
    text="Clear script",
    command=lambda: remove_script(subj_process_dir_entry.get("1.0", 'end-1c').strip(), 'sub-' + subj_entry.get("1.0", 'end-1c').strip()),
    style='Large.TButton',
    width=20
)
remove_script_button.grid(row=0, column=0, padx=(0, 5), pady=(0, 5), sticky='ew')

# Button to append all commands to the script
append_all_commands_button = ttk.Button(
    buttons_frame,
    text="Append all to script",
    command=append_all_commands_to_script,
    style='Large.TButton',
    width=30
)
append_all_commands_button.grid(row=0, column=1, padx=(5, 5), pady=(0, 5), sticky='ew')

# Button to execute commands from the script file
execute_script_button = ttk.Button(
    buttons_frame,
    text="Run selected steps",
    command=execute_all_steps,  # Set the command to the execute_all_steps function
    style='Large.TButton',
    width=30
)
execute_script_button.grid(row=0, column=2, padx=(5, 0), pady=(0, 5), sticky='ew')

# Create a separator
ttk.Separator(main_frame, orient='horizontal').grid(row=(row_num := row_num + 1), columnspan=5, sticky="ew", pady=(10, 5))

# Create a frame for step selection checkboxes
steps_frame = ttk.LabelFrame(main_frame, text="Select processing steps:", padding=10)
steps_frame.grid(row=(row_num := row_num + 1), column=0, columnspan=2, pady=(5, 10), padx=10, sticky='ew')

# Create checkbox variables for each step
step_dcm2bids = tk.BooleanVar(value=True)
step_export_params = tk.BooleanVar(value=True)
step_concatenate = tk.BooleanVar(value=True)
step_denoise = tk.BooleanVar(value=False)
step_degibbs = tk.BooleanVar(value=True)
step_topup = tk.BooleanVar(value=True)
step_masks = tk.BooleanVar(value=True)
step_eddy = tk.BooleanVar(value=True)
step_gnc = tk.BooleanVar(value=True)
step_interpolation = tk.BooleanVar(value=True)
step_MPPCA_noise = tk.BooleanVar(value=True)
step_write_output = tk.BooleanVar(value=True)
step_sandi_division = tk.BooleanVar(value=False)
step_tractcaliber = tk.BooleanVar(value=False)
step_tractseg = tk.BooleanVar(value=False)
step_gnc_anat = tk.BooleanVar(value=False)
step_recon_all = tk.BooleanVar(value=True)

# Create checkboxes in three columns
checkboxes = [
    ("dcm2bids", step_dcm2bids),
    ("export diffusion parameters", step_export_params),
    ("concatenate DWI", step_concatenate),
    ("MP-PCA denoise", step_denoise),
    ("deGibbs", step_degibbs),
    ("topup", step_topup),
    ("generate masks", step_masks),
    ("eddy correction", step_eddy),
    ("GNC DWI", step_gnc),
    ("interpolation", step_interpolation),
    ("MP-PCA noise map", step_MPPCA_noise),
    ("write output", step_write_output),
    ("SANDI volume division", step_sandi_division),
    ("TC volume division", step_tractcaliber),
    ("TractSeg", step_tractseg),
    ("GNC anat", step_gnc_anat),
    ("recon-all", step_recon_all)
]

# Place checkboxes in grid
for i, (text, var) in enumerate(checkboxes):
    row = i % 6
    col = i // 6
    cb = ttk.Checkbutton(steps_frame, text=text, variable=var)
    cb.grid(row=row, column=col, sticky='w', padx=(20, 40), pady=2)


# Make sure the buttons_frame expands to fill the available space
buttons_frame.columnconfigure(0, weight=1)
buttons_frame.columnconfigure(1, weight=1)
buttons_frame.columnconfigure(2, weight=1)


root.mainloop()
